export {default as Home} from './Home'
export {default as Gsap} from './Gsap'
export {default as Curtain} from './Curtain'
export {default as Locomotive} from './Locomotive'
export {default as Uiux} from './Uiux'
export {default as Canvas} from './Canvas'